name: lint
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - snapshot
        ignore_warnings:
          - false
        warnings_as_errors:
          - true
        include:
          - emacs_version: snapshot
            warnings_as_errors: false
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: leotaku/elisp-check@master
        with:
          file: run-command.el
          ignore_warnings: ${{ matrix.ignore_warnings }}
          warnings_as_errors: ${{ matrix.warnings_as_errors }}
